// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDT_Day09_CodeFirst.Models;

#nullable disable

namespace TDT_Day09_CodeFirst.Migrations
{
    [DbContext(typeof(tdtDay09AppContext))]
    partial class tdtDay09AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TDT_Day09_CodeFirst.Models.tdtLoai_San_Pham", b =>
                {
                    b.Property<long>("tdtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tdtId"));

                    b.Property<string>("tdtMaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tdtTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tdtTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("tdtId");

                    b.ToTable("tdtLoai_San_Pham");
                });

            modelBuilder.Entity("TDT_Day09_CodeFirst.Models.tdtSan_Pham", b =>
                {
                    b.Property<long>("tdtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tdtId"));

                    b.Property<decimal>("tdtDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tdtHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("tdtMaLoai")
                        .HasColumnType("bigint");

                    b.Property<string>("tdtMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tdtSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("tdtTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tdtTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("tdtId");

                    b.HasIndex("tdtMaLoai");

                    b.ToTable("tdtSan_Pham");
                });

            modelBuilder.Entity("TDT_Day09_CodeFirst.Models.tdtSan_Pham", b =>
                {
                    b.HasOne("TDT_Day09_CodeFirst.Models.tdtLoai_San_Pham", "tdtLoai_San_Pham")
                        .WithMany("tdtSan_Phams")
                        .HasForeignKey("tdtMaLoai");

                    b.Navigation("tdtLoai_San_Pham");
                });

            modelBuilder.Entity("TDT_Day09_CodeFirst.Models.tdtLoai_San_Pham", b =>
                {
                    b.Navigation("tdtSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
